### ISSUE TITLE
Clatskanie Beta Prep Epic

### ISSUE THREAD

**Issue by jtremback** [althea-net/issue-warehouse#32]
This milestone describes a goal where Deborah is able to add nodes to the node list, but accept payments from people manually. This lets us get the node list into practice without dealing with some remaining payment issues.

- [ ] Cut a release with fixes for router backend IP address issues and router dashboard form field bugs. @ttk2 
- [x] Deploy Aragon App to main net @sebohe 
- [x] Make spreadsheet for ClatskanieCoop @cascadianmesh 
- [x] Questions for Justin: Are we going to main net? What else might need to be prepared for that? @ttk2 
- [x] Get all the users updated (possibly) @cascadianmesh

**Comment by sbc64** [comment]
The app has been installed to the DAO here: https://mainnet.aragon.org/#/clatskanie.aragonid.eth

I'm waiting for addresses from @cascadianmesh and will assign the voting tokens.
